### ISSUE TITLE
Impossible to update PHP files

### ISSUE THREAD

**Issue by Alagaesia93** [pixelgrade/rosa-lite#26]
Hello,

I have this theme installed on my wordpress instance. I created a child theme because I had some changes to do about the title position in the header. Today I have updated the last version and now when I need to edit the files I have this message:

Unable to communicate back with site to check for fatal errors, so the PHP change was reverted. You will need to upload your PHP file change by some other means, such as by using SFTP.

After some google research this seems related to the theme. In fact, if I try to install another theme everything works perfectly.

Can you help me please?

**Comment by georgeolaru** [comment]
@Alagaesia93 Thanks for bringing this up to us!

@vladolaru can you take a look to see if the theme code has anything to do with the errors mentioned above?

**Comment by vladolaru** [comment]
@Alagaesia93 I have checked and the theme doesn't do anything wrong. The thing is it is in general highly discouraged to edit PHP files from within the WordPress dashboard (due to security concerns) and many hosts will block such behavior. 

I recommend you test your alterations locally (using an easy to setup local environment like Local by Flywheel) and then upload the finished child theme files via FTP.

**Comment by Alagaesia93** [comment]
Hello @vladolaru, thank you for reaching back. I can edit files via PHP, but before the last update I could also do updates directly from WP's dashboard. This happens only with your theme, so I decided to report.

I am already editing files via SFTP, thank you :-)

**Comment by vladolaru** [comment]
You are welcome @Alagaesia93 There may be some permissions changes on an update that would prevent PHP from writing those files. SFTP is the best way anyway.
